{{- if .Values.kong.enabled -}}
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rl-by-header
config:
  minute: 1000000
  limit_by: ip
  policy: local
plugin: rate-limiting
{{end}}